apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagggor
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 5
  template:
    metadata:
      name: dagger
      labels:
        app: web-app    # Must be the same as the one in the selector
    spec:
      containers:
        - image: ahmeddagger/nginx
          name: nginx-container
          ports:
            - containerPort: 80
