apiVersion: v1
kind: Pod
metadata:
  name: first
  labels:
    label-name-1: label-value
    another-label: my-app
spec:
  containers:
    - image: ahmeddagger/nginx
      name: nginx-container
      ports:
       - containerPort: 80
      